In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
#import rnn_utils
import random

#import tensorflow.examples.tutorials.mnist.input_data as input_data
#mnist = input_data.read_data_sets("MNIST_data/", one_hot=True) #导入数据

In [2]:
#文件读出来是DataFrame
startarray=pd.read_csv("startarray.csv",header=None)
endarray=pd.read_csv("endarray.csv",header=None)

startarray.columns=['start']
endarray.columns=['end']
#startarray.rename(columns={'start'},inplace=True)
#endarray.rename(columns={'end'},inplace=True)

startarray['start']=startarray['start'].astype(int)
endarray['end']=endarray['end'].astype(int)

#startarray

In [3]:
main=pd.read_table("channel_1.dat",header=None)
#如果不加header=Node，会默认将第一行数据当


In [4]:
type(main[0][0])
tfdata=main[0].str.split(' ',expand=True)
tfdata[0]=pd.to_numeric(tfdata[0])
tfdata[1]=pd.to_numeric(tfdata[1])


In [5]:
tfdata['switch']=0/tfdata[1]
tfdata.columns=['time','mainpower','washerpower']



In [6]:
actitime=pd.read_csv("actitime.csv",header=None)
activalue=pd.read_csv("activalue.csv",header=None)
washeractitime=pd.read_csv("washeractitime.csv",header=None)
washeractivalue=pd.read_csv("washeractivalue.csv",header=None)

actitime.columns=['actitime']
activalue.columns=['value']
washeractitime.columns=['washeractitime']
washeractivalue.columns=['washervalue']
#startarray.rename(columns={'start'},inplace=True)
#endarray.rename(columns={'end'},inplace=True)

actitime['actitime']=actitime['actitime'].astype(int)
activalue['value']=activalue['value'].astype(int)
washeractitime['washeractitime']=washeractitime['washeractitime'].astype(int)
washeractivalue['washervalue']=washeractivalue['washervalue'].astype(int)

In [7]:
tfdata1=tfdata.set_index('time',inplace=False,drop=True)
#tfdata1

In [8]:
tfdata1['mainpower'].min()

46

In [9]:
tfdata1['mainpower'].max()

8423

In [10]:
#x_norm = (x - x_min) / (x_max - x_min)

tfdata1['mainpower']=(tfdata1['mainpower']-tfdata1['mainpower'].min())/(tfdata1['mainpower'].max()-tfdata1['mainpower'].min())
#tfdata1

In [11]:
#listend=[]
#liststart=[]
#drop=0
#long=actitime['actitime'].size-1

#liststart.append(actitime['actitime'][0])

#while(drop<long):
#    if(actitime['actitime'][drop+1]-actitime['actitime'][drop]>8):
#        liststart.append(actitime['actitime'][drop+1])
#        listend.append(actitime['actitime'][drop])
#    drop+=1
#listend.append(actitime['actitime'][long])    

In [12]:
def StartAndEnd(time):
    listend=[]
    liststart=[]
    drop=0
    long=time.size-1
    print(long)
    liststart.append(time[0])

    while(drop<long):
        if(time[drop+1]-time[drop]>8):
            liststart.append(time[drop+1])
            listend.append(time[drop])
        #print(drop)
        drop+=1
    listend.append(time[long]) 
    return liststart,listend

In [13]:
liststart,listend=StartAndEnd(actitime['actitime'])  #只在生成txt时用一次，之后直接读txt的数据

63827


In [ ]:
#washerstart,washerend=StartAndEnd(washeractitime['washeractitime'])//同上
#washerstart

In [ ]:
drop=0
long=len(washerstart)



while(drop<long):
    i=0
    j=len(liststart)
    while(i<j):
        if (liststart[i]>washerstart[drop]and liststart[i]<washerend[drop])or listend[i]>washerstart[drop]and listend[i]<washerend[drop]:
            del washerstart[drop]
            del washerend[drop]
            long=long-1
            break
        i+=1
    drop+=1
    

In [ ]:
#washerstart

In [14]:
drop=0
long=len(liststart)
print(long)
while drop<long:
    if(drop%100==0):
        print(drop)
    tfdata1.loc[liststart[drop]:listend[drop],['washerpower']]=1
    drop+=1


2992
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900


In [15]:
washeron=tfdata1[tfdata1['washerpower']>0.5]
washeroff=tfdata1[tfdata1['washerpower']<0.5]
washeron

mainpower  washerpower
time                              
1357029778   0.334726          1.0
1357029784   0.322430          1.0
1357029790   0.324102          1.0
1357029796   0.332219          1.0
1357029802   0.328877          1.0
1357029808   0.326609          1.0
1357029814   0.321237          1.0
1357029820   0.380327          1.0
1357029826   0.525009          1.0
1357029832   0.521428          1.0
1357029838   0.522144          1.0
1357029843   0.328996          1.0
1357029849   0.324102          1.0
1357029855   0.322311          1.0
1357029861   0.331742          1.0
1357029867   0.325534          1.0
1357029873   0.325176          1.0
1357029879   0.331503          1.0
1357029885   0.331980          1.0
1357029891   0.324699          1.0
1357029897   0.323982          1.0
1357029903   0.064104          1.0
1357029910   0.063985          1.0
1357043052   0.347977          1.0
1357043058   0.339979          1.0
1357043064   0.338665          1.0
1357043070   0.338069          1.0
1357043076   0.336994          1.0
1357043082   0.335084          1.0
1357043088   0.331742          1.0
...               ...          ...
1414655128   0.316939          1.0
1414655134   0.317297          1.0
1414655141   0.312642          1.0
1414655147   0.315745          1.0
1414655154   0.316342          1.0
1414655160   0.311329          1.0
1414655166   0.313597          1.0
1414655173   0.318730          1.0
1414655179   0.316342          1.0
1414655186   0.548764          1.0
1414655192   0.549123          1.0
1414655199   0.547332          1.0
1414655205   0.530620          1.0
1414655211   0.540647          1.0
1414655218   0.366002          1.0
1414655224   0.304644          1.0
1414655231   0.311806          1.0
1414655237   0.310016          1.0
1414655244   0.313836          1.0
1414655250   0.312642          1.0
1414655257   0.311209          1.0
1414655264   0.304047          1.0
1414655270   0.315387          1.0
1414655276   0.319685          1.0
1414655283   0.304405          1.0
1414655290   0.314432          1.0
1414655296   0.314552          1.0
1414655303   0.315268          1.0
1414655309   0.028411          1.0
1414655315   0.031276          1.0

[47182 rows x 2 columns]

In [16]:
washeron=washeron.reset_index()
washeroff=washeroff.reset_index()
#washeron

In [17]:
#washeron['mainpower'][0]
tfdata2=tfdata1

In [18]:

train_x_on=pd.Series(washeron.pop('mainpower'))
train_y_on=pd.Series(washeron.pop('washerpower'))
train_x_off=pd.Series(washeroff.pop('mainpower'))
train_y_off=pd.Series(washeroff.pop('washerpower'))

In [19]:
#超参数

#学习率learning rate
lr=0.0001

#循环次数
training_iters=30000
batch_size=16


In [20]:
n_inputs=1 #每一个时间步输入的是当前时刻的数值
n_steps=128 #6秒一个数值，100个值就是大概10分钟
n_hidden_units=128 #隐藏层单元数，这个不固定，可变动 （说明这个是单层rnn）
n_classes=2 #分类的类数


In [21]:
#tfdata2['mainpower'].loc[1352500095:1352560000].values
p=tfdata2['mainpower'].loc[liststart[0]:listend[0]]
p

time
1357029778    0.334726
1357029784    0.322430
1357029790    0.324102
1357029796    0.332219
1357029802    0.328877
1357029808    0.326609
1357029814    0.321237
1357029820    0.380327
1357029826    0.525009
1357029832    0.521428
1357029838    0.522144
1357029843    0.328996
1357029849    0.324102
1357029855    0.322311
1357029861    0.331742
1357029867    0.325534
1357029873    0.325176
1357029879    0.331503
1357029885    0.331980
1357029891    0.324699
1357029897    0.323982
1357029903    0.064104
1357029910    0.063985
Name: mainpower, dtype: float64

In [22]:
t=listend[0]-liststart[0]
t

144

In [23]:
long=(listend[0]-liststart[0])
many=int(130*6-long)

pp=tfdata2['mainpower'].loc[liststart[0]:listend[0]]
#pp.index.size
#pp.index[0]

#这句十分重要，找到电器开始用的一个在总数据里的那一行（用where函数），然后第一个[0]获取到的是行号数组，由于只需要第一个（也只有一个），所以
#用了第二个[0]来获得其行号，然后就可以利用iloc函数来获取之后的指定个数的行
#np.where(tfdata2.index==pp.index[0])[0][0]
#endline=np.where(tfdata2.index==(pp.index[0]+1))[0][0]
t=np.where(tfdata2.index==(pp.index[0]+1))[0]
t.size

0

In [27]:
def X_on(elec_long,start,end,jianju):#start和end是电器开和关的数组，可能是kettle有可能是washer等。jianju是一个整数，代表每个开关时间内
    #数据抽取的偏移量，对于kettle，数据较多，抽的间隔可以大些，可取3.数据量较少的可选1（最少）
    t=0
   
    
   # p=tfdata2['mainpower'].loc[liststart[0]:(liststart[0]+130)].values.reshape((1,elec_long))
    
    x_on=np.arange(elec_long).reshape(1,elec_long)
    print(len(start))
    while t<len(start):
        long=(end[t]-start[t])
        pp=tfdata2['mainpower'].loc[start[t]:end[t]]
        if pp.size>0:
            size=pp.size
            if size<elec_long:
                many=int(elec_long-size)
                tt=np.where(tfdata2.index==pp.index[0])[0]
                if tt.size>0:
                    endline=tt[0]#liststart所在的行就是最后的起始行。
            
                    startline=endline-(elec_long-size)
           
            #qq=pd.DataFrame({'temp':pp})
                    while startline<=endline:
                
                        x_on=np.row_stack((x_on,tfdata2['mainpower'].iloc[startline:(startline+elec_long)].values.reshape((1,elec_long))))
                        startline+=jianju
            else:
                startline=np.where(tfdata2.index==pp.index[0])[0][0]
                endline=startline+(size-elec_long)
                while startline<=endline:
                
                    x_on=np.row_stack((x_on,tfdata2['mainpower'].iloc[startline:startline+elec_long].values.reshape((1,elec_long))))
                    startline+=jianju
        if t%500==0:
            print(t)
        t+=1
    return x_on
            
            
            

In [24]:
featureson=  np.loadtxt("featureson.txt")


In [25]:
featureson.shape

(112542, 128)

In [30]:
#featureson=X_on(128,liststart,listend,3)

In [31]:
#kettleOff_WasherOn=X_on(128,washerstart,washerend,10)

15794
0
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500
13000
13500
14000
14500
15000
15500


In [32]:
np.delete(kettleOff_WasherOn,0,axis=0)
print(kettleOff_WasherOn.shape)
np.savetxt("kettleOff_FridgeOn.txt",kettleOff_WasherOn)

(180964, 128)


In [ ]:
featureson

In [31]:
np.delete(featureson,0,axis=0)
featureson.shape
np.savetxt("featuresonwasher.txt",featureson)

array([[ 0.02650113,  0.02662051,  0.02638176, ...,  0.32398233,
         0.06410409,  0.06398472],
       [ 0.02602364,  0.02614301,  0.02673988, ...,  0.06255223,
         0.06231348,  0.0617166 ],
       [ 0.02662051,  0.02662051,  0.02590426, ...,  0.06386535,
         0.06135848,  0.06374597],
       ..., 
       [ 0.03819983,  0.03796108,  0.03891608, ...,  0.02041304,
         0.02124866,  0.0168318 ],
       [ 0.03449922,  0.03151486,  0.0346186 , ...,  0.01886117,
         0.02100991,  0.02208428],
       [ 0.0341411 ,  0.03628984,  0.03640922, ...,  0.02136803,
         0.01707055,  0.01874179]])

In [32]:
#featureson=np.ones((train_x_on.size-train_x_on.size%n_steps-n_steps,n_steps))#train_x_on.size-n_steps
#long=train_x_on.size-train_x_on.size%n_steps-n_steps
#drop=0
#while drop<long:
#    temp=random.randint(0,long-1)
#    featureson[drop,:]=train_x_on[drop:(drop+n_steps)].values.reshape((1,n_steps))
#    drop+=1

In [33]:
#Y1=np.zeros((train_x_on.size-train_x_on.size%n_steps-n_steps,2),dtype=np.int)
#Y1[:,0]=1

#dataseton = tf.data.Dataset.from_tensor_slices((featureson,Y1))
#datasetton=dataseton.shuffle(50000)
#datasetton=datasetton.repeat()
#batched_dataseton=datasetton.batch(batch_size)
#iteratoron=batched_dataseton.make_one_shot_iterator()
#next_elementon=iteratoron.get_next()


In [25]:
#size为关的数据里需要用其他大电器开的时候的条数
def OtherElec(size):
    kettleoff_washeron=np.loadtxt("kettleOff_WasherOn.txt")
    kettleoff_fridgeon=np.loadtxt("kettleOff_FridgeOn.txt")
    t=int(size/2)
    np.random.shuffle(kettleoff_washeron)
    np.random.shuffle(kettleoff_fridgeon)
    kettleoff_washeron=kettleoff_washeron[0:t,:]
    kettleoff_fridgeon=kettleoff_fridgeon[0:t,:]
    off=np.vstack((kettleoff_washeron,kettleoff_fridgeon))
    return off


In [26]:
off=OtherElec(55000)

In [27]:
off

array([[ 0.03545422,  0.03557359,  0.03533485, ...,  0.03963233,
         0.03939358,  0.03939358],
       [ 0.0631491 ,  0.0621941 ,  0.06338785, ...,  0.06720783,
         0.06720783,  0.06708846],
       [ 0.32362421,  0.32159484,  0.31932673, ...,  0.04440731,
         0.04440731,  0.04464605],
       ..., 
       [ 0.02506864,  0.02459114,  0.02471052, ...,  0.02471052,
         0.02506864,  0.02506864],
       [ 0.02065178,  0.02100991,  0.02089053, ...,  0.02089053,
         0.02065178,  0.02136803],
       [ 0.02864987,  0.02841113,  0.0285305 , ...,  0.02924675,
         0.02793363,  0.02864987]])

In [28]:
def randomoff(size):
    featuresoff=np.ones((size,n_steps))#train_x_off.size-n_steps,n_steps
#long=train_x_off.size-train_x_off.size%n_steps-n_steps
    drop=0
    while drop<size:
        if(drop%10000==0):
            print(drop)
        featuresoff[drop,:]=np.zeros((1,n_steps))
        temp=random.randint(0,long-1)
        featuresoff[drop,:]=train_x_off[temp:(temp+n_steps)].values.reshape((1,n_steps))
        drop+=1
    return featuresoff

In [29]:
#featuresoff=np.ones((55000,n_steps))#train_x_off.size-n_steps,n_steps
##long=train_x_off.size-train_x_off.size%n_steps-n_steps
#drop=0
#while drop<50000:
#    if(drop%10000==0):
#        print(drop)
#    featuresoff[drop,:]=np.zeros((1,n_steps))
#    temp=random.randint(0,long-1)
#    featuresoff[drop,:]=train_x_off[temp:(temp+n_steps)].values.reshape((1,n_steps))
#    drop+=1
#featuresoff

In [30]:
featuresoff=randomoff(55000)

0
10000
20000
30000
40000
50000


In [31]:
#Y2=np.zeros((100000,2),dtype=np.int)
#Y2[:,1]=1

#datasetoff = tf.data.Dataset.from_tensor_slices((featuresoff,Y2))
#datasettoff=datasetoff.shuffle(250000)
#datasettoff=datasettoff.repeat()
#batched_datasetoff=datasettoff.batch(batch_size)
#iteratoroff=batched_datasetoff.make_one_shot_iterator()
#next_elementoff=iteratoroff.get_next()

In [32]:
featuresoff=np.vstack((off,featuresoff))
featuresoff.shape

(110000, 128)

In [33]:
X=np.vstack([featureson,featuresoff])
X
#X.shape

array([[  0.00000000e+00,   1.00000000e+00,   2.00000000e+00, ...,
          1.25000000e+02,   1.26000000e+02,   1.27000000e+02],
       [  2.65011341e-02,   2.66205085e-02,   2.63817596e-02, ...,
          3.23982333e-01,   6.41040945e-02,   6.39847201e-02],
       [  2.60236361e-02,   2.61430106e-02,   2.67398830e-02, ...,
          6.25522263e-02,   6.23134774e-02,   6.17166050e-02],
       ..., 
       [  5.12116509e-02,   4.93016593e-02,   4.90629103e-02, ...,
          3.59317178e-02,   3.56929688e-02,   3.54542199e-02],
       [  5.74191238e-02,   5.70610004e-02,   5.77772472e-02, ...,
          4.54816760e-02,   3.35442282e-02,   3.42604751e-02],
       [  1.02423302e-01,   1.01229557e-01,   8.75014922e-02, ...,
          3.62898412e-02,   3.56929688e-02,   3.58123433e-02]])

In [34]:
#la=np.zeros((train_x_on.size-train_x_on.size%n_steps-n_steps,1),dtype=np.int)
#lb=np.ones((train_x_on.size-train_x_on.size%n_steps-n_steps,1),dtype=np.int)
la=np.zeros((featureson.shape[0],1),dtype=np.int)
lb=np.ones((featureson.shape[0],1),dtype=np.int)
lc=np.hstack((la,lb))

ld=np.zeros((110000,1),dtype=np.int)
le=np.ones((110000,1),dtype=np.int)
lf=np.hstack((le,ld))
Y=np.vstack((lc,lf))
print(Y)

[[0 1]
 [0 1]
 [0 1]
 ..., 
 [1 0]
 [1 0]
 [1 0]]


In [35]:


dataset = tf.data.Dataset.from_tensor_slices((X,Y))
datasett=dataset.shuffle(200000)
print(datasett.output_shapes)
print(datasett.output_types)
datasett=datasett.repeat()
batched_dataset=datasett.batch(batch_size)
iterator=batched_dataset.make_one_shot_iterator()
next_element=iterator.get_next()

(TensorShape([Dimension(128)]), TensorShape([Dimension(2)]))
(tf.float64, tf.int32)


In [36]:
sess=tf.Session()

In [38]:
def input_X(batch_size,steps,inputs):
    #t=random.random()
    #train_x=0
    Y=0
    halfbatch_size=int(batch_size/2)
   
    #if t>0.5:
    #    train_x=train_x_on
    #    t=1
    #    Y1=np.zeros((batch_size,2),dtype=np.int)
    #    Y[:,0]=1
    Y1=np.zeros((halfbatch_size,2),dtype=np.int)
    Y1[:,0]=1
    #else:
        #train_x=train_x_off
        #t=0
        #Y=np.zeros((batch_size,2),dtype=np.int)
        #Y[:,1]=1
    Y2=np.zeros((halfbatch_size,2),dtype=np.int)
    Y2[:,1]=1
    
        #Y=np.zeros(batch_size * steps * inputs,np.int8)
    #这句是生成了一个100维的随机数，每个随机数代表一个X的开始的下标，往后数100。共batch_size个
    #startpoint=np.random.randint(0,train_x.size-100-1，size=batch_size)
    startpoint1=np.random.randint(0,train_x_on.size-steps-1,size=halfbatch_size)
    startpoint2=np.random.randint(0,train_x_off.size-steps-1,size=halfbatch_size)
    #减100是每个X是100个数，以后改别用硬编码。减1是此函数不包括high
    #train_x[startpoint[i]:startpoint[i]+100]
    
    X=np.arange(batch_size * steps *inputs).reshape(batch_size,steps,inputs)
    
   # y=train_x[startpoint[drop]:(startpoint[drop]+100)].values.reshape((100,1))
     
    long=batch_size
    drop=0
    #print(train_x_on[1357029778])
    while drop<halfbatch_size:
        X[drop,:,:]=np.ones((steps,inputs))*100
        #X[drop,:,:]=train_x_on[startpoint1[drop]:(startpoint1[drop]+steps)].values.reshape((steps,1))
        drop+=1
        
    
    drop=halfbatch_size
    while drop<long:
        X[drop,:,:]=np.ones((steps,inputs))*10
        #X[drop,:,:]=train_x_off[startpoint2[drop-halfbatch_size]:(startpoint2[drop-halfbatch_size]+steps)].values.reshape((steps,1))
        #X[drop,:,:]=train_x_off[startpoint2[drop-halfbatch_size]:(startpoint2[drop-halfbatch_size]+100)].values.reshape((100,1))
        drop+=1
    Y=np.vstack((Y1,Y2))
    #permutation = np.random.permutation(Y.shape[0])
    #X = X[permutation, :, :]
    #Y = Y[permutation]
    
    return X,Y
   
   

In [39]:
#x,y=input_X(128,1500,1)#x即为RNN函数里需要的参数X
#x[0],y[0]


In [40]:
#train_x_on[43755]

In [41]:
def train_input_fn(features, labels, batch_size):
    """An input function for training"""
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

    # Shuffle, repeat, and batch the examples.
    dataset = dataset.shuffle(1000).repeat().batch(batch_size)

    # Build the Iterator, and return the read end of the pipeline.
    return dataset.make_one_shot_iterator().get_next()

In [42]:
#导入数据集

In [37]:
with tf.name_scope('inputs'):  #input
    x = tf.placeholder(tf.float32,[None,n_steps,n_inputs],name='x_inputs')  #得到传递进来的训练样本 
    y = tf.placeholder(tf.float32,[None,n_classes],name='y_inputs') #标签
    weights=\
    {
        'in':tf.Variable(tf.random_normal([n_inputs,n_hidden_units]),name='weights'), #从样本进行输入
        'out':tf.Variable(tf.random_normal([n_hidden_units,n_classes]),name='weights1') #输出至隐藏层
    }
    biases=\
    { #偏置
        'in':tf.Variable(tf.constant(0.1,shape=[n_hidden_units,]),name='biases'), #(128,)
        'out':tf.Variable(tf.constant(0.1,shape=[n_classes,]),name='biases1') #(2,)
    }

def RNN(X,weights,biases):#X（128batch,1steps,100inputs）
    with tf.name_scope('layer'):
        X = tf.reshape(X,[-1,n_inputs]) #重置为128*28,28的向量
        X_in = tf.matmul(X,weights['in'])+biases['in'] #X与weight矩阵乘，加偏置
        X_in = tf.reshape(X_in,[-1,n_steps,n_hidden_units]) #变换形式，置为n*28*128向量
        tf.summary.histogram('X_in', X_in) #储存结果
        #cell
    with tf.name_scope('cell'):
        lstm_cell = tf.contrib.rnn.BasicLSTMCell(n_hidden_units,forget_bias=1.0, state_is_tuple=True) #该层128个cell，偏置 = 1
        _init_state = lstm_cell.zero_state(batch_size,dtype=tf.float32) #初始化
        with tf.variable_scope("rnn",reuse=tf.AUTO_REUSE):
            outputs,states = tf.nn.dynamic_rnn(lstm_cell,X_in,initial_state=_init_state,time_major=False) #输入至cell中
        tf.summary.histogram('outsputs', outputs) #储存输出和状态
        tf.summary.histogram('outsputs', states)
        #输出层
    with tf.name_scope('result'):
        result = tf.matmul(states[1],weights['out'])+biases['out'] #计算结果，将状态与权重（出）相乘，加偏置（出）
        tf.summary.histogram('result', result)
        return result

pred = RNN(x,weights,biases) #调用RNN进行预测

with tf.name_scope('loss'):
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y,logits=pred),name='loss') #求平均值 交叉熵（训练成本）cost
    tf.summary.scalar('loss', cost)
with tf.name_scope('train'):  #进行优化
    train_op = tf.train.AdamOptimizer(lr).minimize(cost) #以lr为学习速度最小化cost   ？？？？？？？？？？？

correct_pred = tf.equal(tf.argmax(pred,1),tf.argmax(y,1)) #比较预测结果和正确答案是否相等，结果为向量
accurary = tf.reduce_mean(tf.cast(correct_pred,tf.float32)) #将correct_pred转化为float32类型，求均值
tf.summary.scalar('accurary', accurary)
init = tf.global_variables_initializer()
saver = tf.train.Saver() #保存模型参数
with tf.Session() as sess: #将sess指向要处理的地方
    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter("logs1/", sess.graph) #打开写文件指针，准备记录
    sess.run(init) #激活，开始训练
    step=0
    while step<1000:
                    # step*batch_size<training_iters:
        t=random.random()
        
        batch_xs,batch_ys = sess.run(next_element) #再取下一个batch块，返回image和label
        
        batch_xs = batch_xs.reshape([batch_size,n_steps,n_inputs]) #同之前操作
        #if step%30==0:
        #    print(batch_xs,batch_ys)
        sess.run(train_op,feed_dict={x:batch_xs,y:batch_ys})
        if step%30==0: #每100步，进行一次记录
            res = sess.run(merged,feed_dict={x:batch_xs,y:batch_ys}) #管理数据
            writer.add_summary(res,step) #记录当前步数和数据
            print(sess.run(accurary,feed_dict={x:batch_xs,y:batch_ys})) #正确率
        step += 1
    save_path = saver.save(sess, "my_net1\save_net.ckpt")

0.625
0.6875
0.5625
0.75
0.875
0.875
0.625
0.75
1.0
0.9375
0.875
1.0
0.875
1.0
1.0
1.0
0.875
0.8125
0.9375
0.875
1.0
1.0
0.9375
1.0
0.9375
1.0
0.9375
0.9375
1.0
0.9375
0.9375
1.0
0.9375
0.9375


In [101]:
t=featuresoff[1:17,:]
print(featureson[1:3,:])
#t.dtype='float32'  用dtype数据会翻倍，坑。要用astype
t=t.astype(np.float32)

t=t.reshape([batch_size,n_steps,n_inputs])

#t.shape
#t.dtype='float32'


k=RNN(t,weights,biases)


[[ 0.02650113  0.02662051  0.02638176  0.02602364  0.02614301  0.02673988
   0.02662051  0.02662051  0.02590426  0.02638176  0.02602364  0.02602364
   0.02626239  0.02638176  0.02518801  0.02506864  0.02506864  0.02542676
   0.02459114  0.02459114  0.02494927  0.02435239  0.02494927  0.02494927
   0.02471052  0.02471052  0.02471052  0.02506864  0.02435239  0.02506864
   0.02447177  0.0238749   0.02494927  0.02506864  0.02435239  0.02435239
   0.02447177  0.0238749   0.02375552  0.02482989  0.02375552  0.02435239
   0.02721738  0.02673988  0.02697863  0.02733676  0.02590426  0.02817238
   0.028053    0.02685926  0.02626239  0.02709801  0.02614301  0.02662051
   0.02542676  0.02530739  0.02518801  0.02423302  0.02542676  0.02482989
   0.02411364  0.02435239  0.02447177  0.02435239  0.02435239  0.0229199
   0.0233974   0.02303927  0.05013728  0.05013728  0.0504954   0.05001791
   0.05037603  0.04989853  0.05001791  0.05037603  0.04810791  0.04870479
   0.04906291  0.04906291  0.04870479  

In [102]:
with tf.Session() as sess:
    saver.restore(sess,"my_net1\save_net.ckpt")
    print(sess.run(tf.argmax(k,1)))

INFO:tensorflow:Restoring parameters from my_net1\save_net.ckpt
[0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0]


In [92]:
#这样不对，w和b仍是调用的是每次随机取值的。因为训练时是在with：里训练的，最终保存到ckpt里了。应该像上面一样读取训练好的模型参数，进行预测。
#sess=tf.Session()
#sess.run(init)
#print(sess.run(weights))#tf.argmax(k,1)

{'in': array([[-0.22301418, -0.28228137,  1.67092085, -0.10127473,  0.40685037,
         0.33482829, -0.89694828, -2.39676714, -0.53803492,  1.0565033 ,
         2.45305538, -0.75428236, -1.01103199, -1.85562456,  0.00968082,
         0.24177141,  0.04019673,  0.83512115, -0.95289075, -1.10424519,
        -1.440817  ,  1.22122037, -0.79013252, -0.30911237,  0.43137267,
         0.02650001,  0.40482971, -0.0869715 , -2.55952048,  0.65558529,
         0.22949573,  1.64180207,  1.22409666, -0.67313248,  0.47240719,
         0.27487037,  2.16365361, -0.18618874,  0.81609201,  0.72237033,
         0.07519566,  0.15769112, -0.46915218, -1.68192053, -0.49305066,
        -0.12250368, -1.76378548, -1.24131811,  0.41829026,  0.13886134,
         0.07300776,  2.66249704,  0.36467999,  0.85094351, -0.82736737,
         0.39196113, -1.30968261, -0.24539427, -0.65627414, -1.16519213,
         0.20964228,  1.84412026, -0.12609755, -0.59118056, -0.28446954,
        -2.11477923, -0.43354607, -0.1333357